# Превращает файлы в массивы байтов C++ (кусками, чтобы строки были короткими)
string(REPLACE "|" ";" FILES "${FILES}")
file(WRITE ${OUT} "// Сгенерировано cmake/embed.cmake — не редактировать\n#include <cstddef>\n")
foreach(f ${FILES})
    get_filename_component(name ${f} NAME_WE)
    string(MAKE_C_IDENTIFIER ${name} id)
    set(path ${SRC_DIR}/${f})
    file(SIZE ${path} size)
    file(APPEND ${OUT} "extern const unsigned char asset_${id}[] = {\n")
    set(off 0)
    while(off LESS size)
        file(READ ${path} chunk OFFSET ${off} LIMIT 1024 HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," chunk "${chunk}")
        file(APPEND ${OUT} "${chunk}\n")
        math(EXPR off "${off} + 1024")
    endwhile()
    file(APPEND ${OUT} "};\nextern const size_t asset_${id}_size = ${size};\n")
endforeach()
